specfile_path: reportd.spec
synced_files:
  - .packit.yml
  - reportd.spec
upstream_package_name: reportd
upstream_project_url: https://github.com/abrt/reportd
downstream_package_name: reportd
jobs:
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branch: fedora-all
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
